### PR TITLE
Issue 322

### LINKED ISSUE #322: Widget to modify OFunction
The main idea: provide the same functionality to write your own functions as in OrientDB console.
So user should be able:

1) Configure function
2) Try to execute that function and see results (as plain json return) without actual saving of that function
3) Save function

Widget should work for new functions and existing in the same manner.
This widget doesn't have any configuration: it should just provide uI for function modification.

### PR DESCRIPTION
**Pull request by ankitbansal**
This fixes #322

### CODE REVIEW

**Comment by PhantomYdn** [comment]
Could you please provide some screenshots? And what are current limitations? Does it work?

**Comment by ankitbansal** [comment]
after_execution
before_execution

**Comment by ankitbansal** [comment]
Rest api is not integrated yet, its a simple function execution result from OFunction.execute.

**Comment by PhantomYdn** [comment]
Ok - please keep this issue as is: I will finalize it.

**Comment by PhantomYdn** [comment]
Done here: https://github.com/OrienteerDW/Orienteer/commit/614b603b12ac16657fba3d57fe5d23541c832ffe

**Pull request closed without merging**
