### PR TITLE
added submodules update command to be executed in maven's intialize phase

### LINKED ISSUE #133: Add wicket-orientdb as a git submodule
This wouldn't interfere with the development of `wicket-orientdb` as a separate project, but due to the fact that the projects are quite close a specific revision could be enforced if it is necessary for a patch in `Orienteer` which is not provided by the maven versioning schema x.y.z or x.y.z-SNAPSHOT.

### PR DESCRIPTION
**Pull request by krichter722**
This should fix #133, merge whenever you're ready, e.g. after 1.0 has been released.

### CODE REVIEW

**Comment by krichter722** [comment]
The travis build fails because the build server can't checkout with SSH URL git@github.com:PhantomYdn/wicket-orientdb.git. This is no issue for a normal user, right? Correct to HTTPS URL or reconfigure travis (possible?)?

**Comment by PhantomYdn** [comment]
Hmm... Hopefully yes - you are right...

**Comment by krichter722** [comment]
Maybe [the "How to get travis to clone git SSH URLs?" question on stackoverflow.com][1] will get this further.

[1]:http://stackoverflow.com/questions/29357764/how-to-get-travis-to-clone-git-ssh-urls

**Comment by PhantomYdn** [comment]
Thanks for the question. Will follow.

**Comment by krichter722** [comment]
Work in my fork (see https://travis-ci.org/krichter722/Orienteer/builds/56506169 for details). Can you restart travis, please (it's not the sharpest guy around when it comes to recognizing repository updates...).

**Comment by PhantomYdn** [comment]
I guess that's because of some merge problem. You can fix that yourself by merging of upstream/master.
In any case I want to spent some time on this git feature before accepting PR...

Btw, can you please share with me why are you interested in Orienteer? Might be I can review priorities in development and so on.

**Comment by krichter722** [comment]
> I guess that's because of some merge problem. You can fix that yourself by merging of upstream/master.
In any case I want to spent some time on this git feature before accepting PR...

I fixed issues in 7637703c7d007152eb99aca34973a051cada82e3, but `travis-ci` runs build with 16068bf (see https://travis-ci.org/PhantomYdn/Orienteer/builds/56506333).

> Btw, can you please share with me why are you interested in Orienteer? Might be I can review priorities in development and so on.

The offer is appreciated, but I can't make any prognose about my future capabilites to contribute (and the current were not that sever imo). I think `orientdb` is great, but the web frontend ("studio") doesn't progress very much for the feature I'm missing, so I was happy to find an alternative written in Java and wanted to support it.

**Comment by krichter722** [comment]
I finally figured it out :) Take the time to get started with submodules. I messed up badly before the last commit, but with the current project structure it just make a lot of sense to use such.

**Comment by PhantomYdn** [comment]
git feature was checked. It's not for now. Issue might be reopened if some real-life cases occur.

**Pull request closed without merging**
